/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model;


import com.myStore.Warehouse.model.tables.WarehouseProductDetail;
import com.myStore.Warehouse.model.tables.WarehouseProductOrder;
import com.myStore.Warehouse.model.tables.records.WarehouseProductDetailRecord;
import com.myStore.Warehouse.model.tables.records.WarehouseProductOrderRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<WarehouseProductDetailRecord, Integer> IDENTITY_WAREHOUSE_PRODUCT_DETAIL = Identities0.IDENTITY_WAREHOUSE_PRODUCT_DETAIL;
    public static final Identity<WarehouseProductOrderRecord, Integer> IDENTITY_WAREHOUSE_PRODUCT_ORDER = Identities0.IDENTITY_WAREHOUSE_PRODUCT_ORDER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<WarehouseProductDetailRecord> CONSTRAINT_2 = UniqueKeys0.CONSTRAINT_2;
    public static final UniqueKey<WarehouseProductOrderRecord> CONSTRAINT_8 = UniqueKeys0.CONSTRAINT_8;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<WarehouseProductDetailRecord, Integer> IDENTITY_WAREHOUSE_PRODUCT_DETAIL = createIdentity(WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL, WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL.ID);
        public static Identity<WarehouseProductOrderRecord, Integer> IDENTITY_WAREHOUSE_PRODUCT_ORDER = createIdentity(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER, WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<WarehouseProductDetailRecord> CONSTRAINT_2 = createUniqueKey(WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL, "CONSTRAINT_2", WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL.ID);
        public static final UniqueKey<WarehouseProductOrderRecord> CONSTRAINT_8 = createUniqueKey(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER, "CONSTRAINT_8", WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.ID);
    }
}
