/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model;


import com.myStore.Warehouse.model.tables.WarehouseProductDetail;
import com.myStore.Warehouse.model.tables.WarehouseProductOrder;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1739066682;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL</code>.
     */
    public final WarehouseProductDetail WAREHOUSE_PRODUCT_DETAIL = com.myStore.Warehouse.model.tables.WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL;

    /**
     * The table <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER</code>.
     */
    public final WarehouseProductOrder WAREHOUSE_PRODUCT_ORDER = com.myStore.Warehouse.model.tables.WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SYSTEM_SEQUENCE_95C0914A_2F18_4581_A0B9_D66B91DA9B11,
            Sequences.SYSTEM_SEQUENCE_9CE9BCBA_8971_4EED_8B20_C94FC480A371);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL,
            WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER);
    }
}
