/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_95C0914A_2F18_4581_A0B9_D66B91DA9B11</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_95C0914A_2F18_4581_A0B9_D66B91DA9B11 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_95C0914A_2F18_4581_A0B9_D66B91DA9B11", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_9CE9BCBA_8971_4EED_8B20_C94FC480A371</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_9CE9BCBA_8971_4EED_8B20_C94FC480A371 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_9CE9BCBA_8971_4EED_8B20_C94FC480A371", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
