/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model;


import com.myStore.Warehouse.model.tables.WarehouseProductDetail;
import com.myStore.Warehouse.model.tables.WarehouseProductOrder;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL</code>.
     */
    public static final WarehouseProductDetail WAREHOUSE_PRODUCT_DETAIL = com.myStore.Warehouse.model.tables.WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL;

    /**
     * The table <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER</code>.
     */
    public static final WarehouseProductOrder WAREHOUSE_PRODUCT_ORDER = com.myStore.Warehouse.model.tables.WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER;
}
