/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model.tables.daos;


import com.myStore.ProductManagement.model.tables.Category;
import com.myStore.ProductManagement.model.tables.records.CategoryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryDao extends DAOImpl<CategoryRecord, com.myStore.ProductManagement.model.tables.pojos.Category, Integer> {

    /**
     * Create a new CategoryDao without any configuration
     */
    public CategoryDao() {
        super(Category.CATEGORY, com.myStore.ProductManagement.model.tables.pojos.Category.class);
    }

    /**
     * Create a new CategoryDao with an attached configuration
     */
    public CategoryDao(Configuration configuration) {
        super(Category.CATEGORY, com.myStore.ProductManagement.model.tables.pojos.Category.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.myStore.ProductManagement.model.tables.pojos.Category object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Category> fetchById(Integer... values) {
        return fetch(Category.CATEGORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.myStore.ProductManagement.model.tables.pojos.Category fetchOneById(Integer value) {
        return fetchOne(Category.CATEGORY.ID, value);
    }

    /**
     * Fetch records that have <code>CODE IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Category> fetchByCode(String... values) {
        return fetch(Category.CATEGORY.CODE, values);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Category> fetchByName(String... values) {
        return fetch(Category.CATEGORY.NAME, values);
    }

    /**
     * Fetch records that have <code>CREATE_TS IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Category> fetchByCreateTs(Timestamp... values) {
        return fetch(Category.CATEGORY.CREATE_TS, values);
    }

    /**
     * Fetch records that have <code>CREATE_BY IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Category> fetchByCreateBy(String... values) {
        return fetch(Category.CATEGORY.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>UPDATE_TS IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Category> fetchByUpdateTs(Timestamp... values) {
        return fetch(Category.CATEGORY.UPDATE_TS, values);
    }

    /**
     * Fetch records that have <code>UPDATE_BY IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Category> fetchByUpdateBy(String... values) {
        return fetch(Category.CATEGORY.UPDATE_BY, values);
    }
}
