/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model.tables.daos;


import com.myStore.ProductManagement.model.tables.Product;
import com.myStore.ProductManagement.model.tables.records.ProductRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductDao extends DAOImpl<ProductRecord, com.myStore.ProductManagement.model.tables.pojos.Product, Integer> {

    /**
     * Create a new ProductDao without any configuration
     */
    public ProductDao() {
        super(Product.PRODUCT, com.myStore.ProductManagement.model.tables.pojos.Product.class);
    }

    /**
     * Create a new ProductDao with an attached configuration
     */
    public ProductDao(Configuration configuration) {
        super(Product.PRODUCT, com.myStore.ProductManagement.model.tables.pojos.Product.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.myStore.ProductManagement.model.tables.pojos.Product object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Product> fetchById(Integer... values) {
        return fetch(Product.PRODUCT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.myStore.ProductManagement.model.tables.pojos.Product fetchOneById(Integer value) {
        return fetchOne(Product.PRODUCT.ID, value);
    }

    /**
     * Fetch records that have <code>CODE IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Product> fetchByCode(String... values) {
        return fetch(Product.PRODUCT.CODE, values);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Product> fetchByName(String... values) {
        return fetch(Product.PRODUCT.NAME, values);
    }

    /**
     * Fetch records that have <code>CREATE_TS IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Product> fetchByCreateTs(Timestamp... values) {
        return fetch(Product.PRODUCT.CREATE_TS, values);
    }

    /**
     * Fetch records that have <code>CREATE_BY IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Product> fetchByCreateBy(String... values) {
        return fetch(Product.PRODUCT.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>UPDATE_TS IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Product> fetchByUpdateTs(Timestamp... values) {
        return fetch(Product.PRODUCT.UPDATE_TS, values);
    }

    /**
     * Fetch records that have <code>UPDATE_BY IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.Product> fetchByUpdateBy(String... values) {
        return fetch(Product.PRODUCT.UPDATE_BY, values);
    }
}
