/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model.tables.daos;


import com.myStore.ProductManagement.model.tables.ProductCategory;
import com.myStore.ProductManagement.model.tables.records.ProductCategoryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryDao extends DAOImpl<ProductCategoryRecord, com.myStore.ProductManagement.model.tables.pojos.ProductCategory, Integer> {

    /**
     * Create a new ProductCategoryDao without any configuration
     */
    public ProductCategoryDao() {
        super(ProductCategory.PRODUCT_CATEGORY, com.myStore.ProductManagement.model.tables.pojos.ProductCategory.class);
    }

    /**
     * Create a new ProductCategoryDao with an attached configuration
     */
    public ProductCategoryDao(Configuration configuration) {
        super(ProductCategory.PRODUCT_CATEGORY, com.myStore.ProductManagement.model.tables.pojos.ProductCategory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.myStore.ProductManagement.model.tables.pojos.ProductCategory object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.ProductCategory> fetchById(Integer... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.myStore.ProductManagement.model.tables.pojos.ProductCategory fetchOneById(Integer value) {
        return fetchOne(ProductCategory.PRODUCT_CATEGORY.ID, value);
    }

    /**
     * Fetch records that have <code>PRODUCT_ID IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.ProductCategory> fetchByProductId(Integer... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.PRODUCT_ID, values);
    }

    /**
     * Fetch records that have <code>CATEGORY_ID IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.ProductCategory> fetchByCategoryId(Integer... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>CREATE_TS IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.ProductCategory> fetchByCreateTs(Timestamp... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.CREATE_TS, values);
    }

    /**
     * Fetch records that have <code>CREATE_BY IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.ProductCategory> fetchByCreateBy(String... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>UPDATE_TS IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.ProductCategory> fetchByUpdateTs(Timestamp... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.UPDATE_TS, values);
    }

    /**
     * Fetch records that have <code>UPDATE_BY IN (values)</code>
     */
    public List<com.myStore.ProductManagement.model.tables.pojos.ProductCategory> fetchByUpdateBy(String... values) {
        return fetch(ProductCategory.PRODUCT_CATEGORY.UPDATE_BY, values);
    }
}
