/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model.tables;


import com.myStore.Warehouse.model.Keys;
import com.myStore.Warehouse.model.Public;
import com.myStore.Warehouse.model.tables.records.WarehouseProductOrderRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WarehouseProductOrder extends TableImpl<WarehouseProductOrderRecord> {

    private static final long serialVersionUID = -1958180743;

    /**
     * The reference instance of <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER</code>
     */
    public static final WarehouseProductOrder WAREHOUSE_PRODUCT_ORDER = new WarehouseProductOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WarehouseProductOrderRecord> getRecordType() {
        return WarehouseProductOrderRecord.class;
    }

    /**
     * The column <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.ID</code>.
     */
    public final TableField<WarehouseProductOrderRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.TIMESTAMP</code>.
     */
    public final TableField<WarehouseProductOrderRecord, Timestamp> TIMESTAMP = createField("TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.STATUS</code>.
     */
    public final TableField<WarehouseProductOrderRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.PRODUCT_ID</code>.
     */
    public final TableField<WarehouseProductOrderRecord, Integer> PRODUCT_ID = createField("PRODUCT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER</code> table reference
     */
    public WarehouseProductOrder() {
        this("WAREHOUSE_PRODUCT_ORDER", null);
    }

    /**
     * Create an aliased <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER</code> table reference
     */
    public WarehouseProductOrder(String alias) {
        this(alias, WAREHOUSE_PRODUCT_ORDER);
    }

    private WarehouseProductOrder(String alias, Table<WarehouseProductOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private WarehouseProductOrder(String alias, Table<WarehouseProductOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WarehouseProductOrderRecord, Integer> getIdentity() {
        return Keys.IDENTITY_WAREHOUSE_PRODUCT_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WarehouseProductOrderRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WarehouseProductOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<WarehouseProductOrderRecord>>asList(Keys.CONSTRAINT_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductOrder as(String alias) {
        return new WarehouseProductOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public WarehouseProductOrder rename(String name) {
        return new WarehouseProductOrder(name, null);
    }
}
