/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WarehouseProductDetail implements Serializable {

    private static final long serialVersionUID = -1894195123;

    private Integer id;
    private Integer productId;
    private Integer availableStocks;
    private Double  price;

    public WarehouseProductDetail() {}

    public WarehouseProductDetail(WarehouseProductDetail value) {
        this.id = value.id;
        this.productId = value.productId;
        this.availableStocks = value.availableStocks;
        this.price = value.price;
    }

    public WarehouseProductDetail(
        Integer id,
        Integer productId,
        Integer availableStocks,
        Double  price
    ) {
        this.id = id;
        this.productId = productId;
        this.availableStocks = availableStocks;
        this.price = price;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getAvailableStocks() {
        return this.availableStocks;
    }

    public void setAvailableStocks(Integer availableStocks) {
        this.availableStocks = availableStocks;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WarehouseProductDetail (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(availableStocks);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
