/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WarehouseProductOrder implements Serializable {

    private static final long serialVersionUID = -50173816;

    private Integer   id;
    private Timestamp timestamp;
    private String    status;
    private Integer   productId;

    public WarehouseProductOrder() {}

    public WarehouseProductOrder(WarehouseProductOrder value) {
        this.id = value.id;
        this.timestamp = value.timestamp;
        this.status = value.status;
        this.productId = value.productId;
    }

    public WarehouseProductOrder(
        Integer   id,
        Timestamp timestamp,
        String    status,
        Integer   productId
    ) {
        this.id = id;
        this.timestamp = timestamp;
        this.status = status;
        this.productId = productId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("WarehouseProductOrder (");

        sb.append(id);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(status);
        sb.append(", ").append(productId);

        sb.append(")");
        return sb.toString();
    }
}
