/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model.tables.records;


import com.myStore.ProductManagement.model.tables.Product;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record7<Integer, String, String, Timestamp, String, Timestamp, String> {

    private static final long serialVersionUID = 1011298326;

    /**
     * Setter for <code>PRDMGT.PRODUCT.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PRDMGT.PRODUCT.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PRDMGT.PRODUCT.CODE</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PRDMGT.PRODUCT.CODE</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PRDMGT.PRODUCT.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PRDMGT.PRODUCT.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PRDMGT.PRODUCT.CREATE_TS</code>.
     */
    public void setCreateTs(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>PRDMGT.PRODUCT.CREATE_TS</code>.
     */
    public Timestamp getCreateTs() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>PRDMGT.PRODUCT.CREATE_BY</code>.
     */
    public void setCreateBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PRDMGT.PRODUCT.CREATE_BY</code>.
     */
    public String getCreateBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PRDMGT.PRODUCT.UPDATE_TS</code>.
     */
    public void setUpdateTs(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>PRDMGT.PRODUCT.UPDATE_TS</code>.
     */
    public Timestamp getUpdateTs() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>PRDMGT.PRODUCT.UPDATE_BY</code>.
     */
    public void setUpdateBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PRDMGT.PRODUCT.UPDATE_BY</code>.
     */
    public String getUpdateBy() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Timestamp, String, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Timestamp, String, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Product.PRODUCT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Product.PRODUCT.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Product.PRODUCT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Product.PRODUCT.CREATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Product.PRODUCT.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Product.PRODUCT.UPDATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Product.PRODUCT.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value4(Timestamp value) {
        setCreateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value5(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value6(Timestamp value) {
        setUpdateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value7(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(Integer value1, String value2, String value3, Timestamp value4, String value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Integer id, String code, String name, Timestamp createTs, String createBy, Timestamp updateTs, String updateBy) {
        super(Product.PRODUCT);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, createTs);
        set(4, createBy);
        set(5, updateTs);
        set(6, updateBy);
    }
}
