/*
* DDL Scripts for creating tables for warehouse microservice app
* Crated By: Arvin Lowel Jalimao
* Last Update Date: 10/25/2017
*/
/*START H2 DB */
DROP TABLE WAREHOUSE_PRODUCT_ORDER

IF EXISTS;
	CREATE TABLE WAREHOUSE_PRODUCT_ORDER (
		ID INT auto_increment PRIMARY KEY
		,"TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
		,STATUS VARCHAR(255) NOT NULL
		,PRODUCT_ID INT NOT NULL
		);

INSERT INTO WAREHOUSE_PRODUCT_ORDER (STATUS, PRODUCT_ID) VALUES ('OPEN', 1);
--SELECT * FROM WAREHOUSE_PRODUCT_ORDER; 

DROP TABLE WAREHOUSE_PRODUCT_DETAIL

IF EXISTS;
	CREATE TABLE WAREHOUSE_PRODUCT_DETAIL (
		ID INT auto_increment PRIMARY KEY
		,PRODUCT_ID INT
		,AVAILABLE_STOCKS INT
		,PRICE DOUBLE
		);
		
INSERT INTO WAREHOUSE_PRODUCT_DETAIL (PRODUCT_ID, AVAILABLE_STOCKS, PRICE) VALUES (1, 2, 10.50);
--SELECT * FROM WAREHOUSE_PRODUCT_DETAIL ;
/*END H2 DB */

/*START POSTGRESQL DB */
DROP TABLE IF EXISTS WAREHOUSE_PRODUCT_ORDER;

	CREATE TABLE WAREHOUSE_PRODUCT_ORDER (
		ID SERIAL  PRIMARY KEY
		,"TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		,STATUS VARCHAR(255)
		,PRODUCT_ID INT
		);

INSERT INTO WAREHOUSE_PRODUCT_ORDER (STATUS, PRODUCT_ID) VALUES ('OPEN', 1);
--SELECT * FROM WAREHOUSE_PRODUCT_ORDER; 

DROP TABLE IF EXISTS WAREHOUSE_PRODUCT_DETAIL;
	CREATE TABLE WAREHOUSE_PRODUCT_DETAIL (
		ID SERIAL PRIMARY KEY
		,PRODUCT_ID INT
		,AVAILABLE_STOCKS INT
		,PRICE DECIMAL
		);
		
INSERT INTO WAREHOUSE_PRODUCT_DETAIL (PRODUCT_ID, AVAILABLE_STOCKS, PRICE) VALUES (1, 2, 10.50);
/*END POSTGRESQL DB*/
