/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model.tables.daos;


import com.myStore.Warehouse.model.tables.WarehouseProductOrder;
import com.myStore.Warehouse.model.tables.records.WarehouseProductOrderRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WarehouseProductOrderDao extends DAOImpl<WarehouseProductOrderRecord, com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder, Integer> {

    /**
     * Create a new WarehouseProductOrderDao without any configuration
     */
    public WarehouseProductOrderDao() {
        super(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER, com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder.class);
    }

    /**
     * Create a new WarehouseProductOrderDao with an attached configuration
     */
    public WarehouseProductOrderDao(Configuration configuration) {
        super(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER, com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder> fetchById(Integer... values) {
        return fetch(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder fetchOneById(Integer value) {
        return fetchOne(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.ID, value);
    }

    /**
     * Fetch records that have <code>TIMESTAMP IN (values)</code>
     */
    public List<com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder> fetchByTimestamp(Timestamp... values) {
        return fetch(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder> fetchByStatus(String... values) {
        return fetch(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.STATUS, values);
    }

    /**
     * Fetch records that have <code>PRODUCT_ID IN (values)</code>
     */
    public List<com.myStore.Warehouse.model.tables.pojos.WarehouseProductOrder> fetchByProductId(Integer... values) {
        return fetch(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.PRODUCT_ID, values);
    }
}
