/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Category implements Serializable {

    private static final long serialVersionUID = 2125477057;

    private Integer   id;
    private String    code;
    private String    name;
    private Timestamp createTs;
    private String    createBy;
    private Timestamp updateTs;
    private String    updateBy;

    public Category() {}

    public Category(Category value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.createTs = value.createTs;
        this.createBy = value.createBy;
        this.updateTs = value.updateTs;
        this.updateBy = value.updateBy;
    }

    public Category(
        Integer   id,
        String    code,
        String    name,
        Timestamp createTs,
        String    createBy,
        Timestamp updateTs,
        String    updateBy
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.createTs = createTs;
        this.createBy = createBy;
        this.updateTs = updateTs;
        this.updateBy = updateBy;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getCreateTs() {
        return this.createTs;
    }

    public void setCreateTs(Timestamp createTs) {
        this.createTs = createTs;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getUpdateTs() {
        return this.updateTs;
    }

    public void setUpdateTs(Timestamp updateTs) {
        this.updateTs = updateTs;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Category (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(createTs);
        sb.append(", ").append(createBy);
        sb.append(", ").append(updateTs);
        sb.append(", ").append(updateBy);

        sb.append(")");
        return sb.toString();
    }
}
