/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategory implements Serializable {

    private static final long serialVersionUID = 315469478;

    private Integer   id;
    private Integer   productId;
    private Integer   categoryId;
    private Timestamp createTs;
    private String    createBy;
    private Timestamp updateTs;
    private String    updateBy;

    public ProductCategory() {}

    public ProductCategory(ProductCategory value) {
        this.id = value.id;
        this.productId = value.productId;
        this.categoryId = value.categoryId;
        this.createTs = value.createTs;
        this.createBy = value.createBy;
        this.updateTs = value.updateTs;
        this.updateBy = value.updateBy;
    }

    public ProductCategory(
        Integer   id,
        Integer   productId,
        Integer   categoryId,
        Timestamp createTs,
        String    createBy,
        Timestamp updateTs,
        String    updateBy
    ) {
        this.id = id;
        this.productId = productId;
        this.categoryId = categoryId;
        this.createTs = createTs;
        this.createBy = createBy;
        this.updateTs = updateTs;
        this.updateBy = updateBy;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public Timestamp getCreateTs() {
        return this.createTs;
    }

    public void setCreateTs(Timestamp createTs) {
        this.createTs = createTs;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Timestamp getUpdateTs() {
        return this.updateTs;
    }

    public void setUpdateTs(Timestamp updateTs) {
        this.updateTs = updateTs;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductCategory (");

        sb.append(id);
        sb.append(", ").append(productId);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(createTs);
        sb.append(", ").append(createBy);
        sb.append(", ").append(updateTs);
        sb.append(", ").append(updateBy);

        sb.append(")");
        return sb.toString();
    }
}
