/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model.tables;


import com.myStore.ProductManagement.model.Keys;
import com.myStore.ProductManagement.model.Prdmgt;
import com.myStore.ProductManagement.model.tables.records.CategoryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Category extends TableImpl<CategoryRecord> {

    private static final long serialVersionUID = 1234482812;

    /**
     * The reference instance of <code>PRDMGT.CATEGORY</code>
     */
    public static final Category CATEGORY = new Category();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CategoryRecord> getRecordType() {
        return CategoryRecord.class;
    }

    /**
     * The column <code>PRDMGT.CATEGORY.ID</code>.
     */
    public final TableField<CategoryRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PRDMGT.CATEGORY.CODE</code>.
     */
    public final TableField<CategoryRecord, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>PRDMGT.CATEGORY.NAME</code>.
     */
    public final TableField<CategoryRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>PRDMGT.CATEGORY.CREATE_TS</code>.
     */
    public final TableField<CategoryRecord, Timestamp> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PRDMGT.CATEGORY.CREATE_BY</code>.
     */
    public final TableField<CategoryRecord, String> CREATE_BY = createField("CREATE_BY", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>PRDMGT.CATEGORY.UPDATE_TS</code>.
     */
    public final TableField<CategoryRecord, Timestamp> UPDATE_TS = createField("UPDATE_TS", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PRDMGT.CATEGORY.UPDATE_BY</code>.
     */
    public final TableField<CategoryRecord, String> UPDATE_BY = createField("UPDATE_BY", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>PRDMGT.CATEGORY</code> table reference
     */
    public Category() {
        this("CATEGORY", null);
    }

    /**
     * Create an aliased <code>PRDMGT.CATEGORY</code> table reference
     */
    public Category(String alias) {
        this(alias, CATEGORY);
    }

    private Category(String alias, Table<CategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Category(String alias, Table<CategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Prdmgt.PRDMGT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CategoryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CategoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<CategoryRecord>>asList(Keys.CONSTRAINT_3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Category as(String alias) {
        return new Category(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Category rename(String name) {
        return new Category(name, null);
    }
}
