/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model.tables;


import com.myStore.ProductManagement.model.Keys;
import com.myStore.ProductManagement.model.Prdmgt;
import com.myStore.ProductManagement.model.tables.records.ProductCategoryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategory extends TableImpl<ProductCategoryRecord> {

    private static final long serialVersionUID = -343449743;

    /**
     * The reference instance of <code>PRDMGT.PRODUCT_CATEGORY</code>
     */
    public static final ProductCategory PRODUCT_CATEGORY = new ProductCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductCategoryRecord> getRecordType() {
        return ProductCategoryRecord.class;
    }

    /**
     * The column <code>PRDMGT.PRODUCT_CATEGORY.ID</code>.
     */
    public final TableField<ProductCategoryRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PRDMGT.PRODUCT_CATEGORY.PRODUCT_ID</code>.
     */
    public final TableField<ProductCategoryRecord, Integer> PRODUCT_ID = createField("PRODUCT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PRDMGT.PRODUCT_CATEGORY.CATEGORY_ID</code>.
     */
    public final TableField<ProductCategoryRecord, Integer> CATEGORY_ID = createField("CATEGORY_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PRDMGT.PRODUCT_CATEGORY.CREATE_TS</code>.
     */
    public final TableField<ProductCategoryRecord, Timestamp> CREATE_TS = createField("CREATE_TS", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PRDMGT.PRODUCT_CATEGORY.CREATE_BY</code>.
     */
    public final TableField<ProductCategoryRecord, String> CREATE_BY = createField("CREATE_BY", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>PRDMGT.PRODUCT_CATEGORY.UPDATE_TS</code>.
     */
    public final TableField<ProductCategoryRecord, Timestamp> UPDATE_TS = createField("UPDATE_TS", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>PRDMGT.PRODUCT_CATEGORY.UPDATE_BY</code>.
     */
    public final TableField<ProductCategoryRecord, String> UPDATE_BY = createField("UPDATE_BY", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>PRDMGT.PRODUCT_CATEGORY</code> table reference
     */
    public ProductCategory() {
        this("PRODUCT_CATEGORY", null);
    }

    /**
     * Create an aliased <code>PRDMGT.PRODUCT_CATEGORY</code> table reference
     */
    public ProductCategory(String alias) {
        this(alias, PRODUCT_CATEGORY);
    }

    private ProductCategory(String alias, Table<ProductCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductCategory(String alias, Table<ProductCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Prdmgt.PRDMGT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProductCategoryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PRODUCT_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductCategoryRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_39;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductCategoryRecord>>asList(Keys.CONSTRAINT_39);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProductCategoryRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProductCategoryRecord, ?>>asList(Keys.CONSTRAINT_391, Keys.CONSTRAINT_3919);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategory as(String alias) {
        return new ProductCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductCategory rename(String name) {
        return new ProductCategory(name, null);
    }
}
