/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model.tables.records;


import com.myStore.Warehouse.model.tables.WarehouseProductOrder;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WarehouseProductOrderRecord extends UpdatableRecordImpl<WarehouseProductOrderRecord> implements Record4<Integer, Timestamp, String, Integer> {

    private static final long serialVersionUID = -399087378;

    /**
     * Setter for <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.TIMESTAMP</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.TIMESTAMP</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.STATUS</code>.
     */
    public void setStatus(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.PRODUCT_ID</code>.
     */
    public void setProductId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.WAREHOUSE_PRODUCT_ORDER.PRODUCT_ID</code>.
     */
    public Integer getProductId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductOrderRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductOrderRecord value2(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductOrderRecord value3(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductOrderRecord value4(Integer value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductOrderRecord values(Integer value1, Timestamp value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WarehouseProductOrderRecord
     */
    public WarehouseProductOrderRecord() {
        super(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER);
    }

    /**
     * Create a detached, initialised WarehouseProductOrderRecord
     */
    public WarehouseProductOrderRecord(Integer id, Timestamp timestamp, String status, Integer productId) {
        super(WarehouseProductOrder.WAREHOUSE_PRODUCT_ORDER);

        set(0, id);
        set(1, timestamp);
        set(2, status);
        set(3, productId);
    }
}
