/*
 * This file is generated by jOOQ.
*/
package com.myStore.Warehouse.model.tables.records;


import com.myStore.Warehouse.model.tables.WarehouseProductDetail;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WarehouseProductDetailRecord extends UpdatableRecordImpl<WarehouseProductDetailRecord> implements Record4<Integer, Integer, Integer, Double> {

    private static final long serialVersionUID = 1489723192;

    /**
     * Setter for <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL.PRODUCT_ID</code>.
     */
    public void setProductId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL.PRODUCT_ID</code>.
     */
    public Integer getProductId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL.AVAILABLE_STOCKS</code>.
     */
    public void setAvailableStocks(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL.AVAILABLE_STOCKS</code>.
     */
    public Integer getAvailableStocks() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL.PRICE</code>.
     */
    public void setPrice(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.WAREHOUSE_PRODUCT_DETAIL.PRICE</code>.
     */
    public Double getPrice() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL.AVAILABLE_STOCKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAvailableStocks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductDetailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductDetailRecord value2(Integer value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductDetailRecord value3(Integer value) {
        setAvailableStocks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductDetailRecord value4(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WarehouseProductDetailRecord values(Integer value1, Integer value2, Integer value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WarehouseProductDetailRecord
     */
    public WarehouseProductDetailRecord() {
        super(WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL);
    }

    /**
     * Create a detached, initialised WarehouseProductDetailRecord
     */
    public WarehouseProductDetailRecord(Integer id, Integer productId, Integer availableStocks, Double price) {
        super(WarehouseProductDetail.WAREHOUSE_PRODUCT_DETAIL);

        set(0, id);
        set(1, productId);
        set(2, availableStocks);
        set(3, price);
    }
}
