/*
 * This file is generated by jOOQ.
*/
package com.myStore.ProductManagement.model;


import com.myStore.ProductManagement.model.tables.Category;
import com.myStore.ProductManagement.model.tables.Product;
import com.myStore.ProductManagement.model.tables.ProductCategory;
import com.myStore.ProductManagement.model.tables.records.CategoryRecord;
import com.myStore.ProductManagement.model.tables.records.ProductCategoryRecord;
import com.myStore.ProductManagement.model.tables.records.ProductRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PRDMGT</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CategoryRecord, Integer> IDENTITY_CATEGORY = Identities0.IDENTITY_CATEGORY;
    public static final Identity<ProductRecord, Integer> IDENTITY_PRODUCT = Identities0.IDENTITY_PRODUCT;
    public static final Identity<ProductCategoryRecord, Integer> IDENTITY_PRODUCT_CATEGORY = Identities0.IDENTITY_PRODUCT_CATEGORY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoryRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<ProductRecord> CONSTRAINT_1 = UniqueKeys0.CONSTRAINT_1;
    public static final UniqueKey<ProductCategoryRecord> CONSTRAINT_39 = UniqueKeys0.CONSTRAINT_39;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ProductCategoryRecord, ProductRecord> CONSTRAINT_391 = ForeignKeys0.CONSTRAINT_391;
    public static final ForeignKey<ProductCategoryRecord, CategoryRecord> CONSTRAINT_3919 = ForeignKeys0.CONSTRAINT_3919;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<CategoryRecord, Integer> IDENTITY_CATEGORY = createIdentity(Category.CATEGORY, Category.CATEGORY.ID);
        public static Identity<ProductRecord, Integer> IDENTITY_PRODUCT = createIdentity(Product.PRODUCT, Product.PRODUCT.ID);
        public static Identity<ProductCategoryRecord, Integer> IDENTITY_PRODUCT_CATEGORY = createIdentity(ProductCategory.PRODUCT_CATEGORY, ProductCategory.PRODUCT_CATEGORY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<CategoryRecord> CONSTRAINT_3 = createUniqueKey(Category.CATEGORY, "CONSTRAINT_3", Category.CATEGORY.ID);
        public static final UniqueKey<ProductRecord> CONSTRAINT_1 = createUniqueKey(Product.PRODUCT, "CONSTRAINT_1", Product.PRODUCT.ID);
        public static final UniqueKey<ProductCategoryRecord> CONSTRAINT_39 = createUniqueKey(ProductCategory.PRODUCT_CATEGORY, "CONSTRAINT_39", ProductCategory.PRODUCT_CATEGORY.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ProductCategoryRecord, ProductRecord> CONSTRAINT_391 = createForeignKey(com.myStore.ProductManagement.model.Keys.CONSTRAINT_1, ProductCategory.PRODUCT_CATEGORY, "CONSTRAINT_391", ProductCategory.PRODUCT_CATEGORY.PRODUCT_ID);
        public static final ForeignKey<ProductCategoryRecord, CategoryRecord> CONSTRAINT_3919 = createForeignKey(com.myStore.ProductManagement.model.Keys.CONSTRAINT_3, ProductCategory.PRODUCT_CATEGORY, "CONSTRAINT_3919", ProductCategory.PRODUCT_CATEGORY.CATEGORY_ID);
    }
}
